---
fixtures:
  repositories:
    datacat: 'https://github.com/richardc/puppet-datacat.git'
    stdlib: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
    concat: 'git://github.com/ripienaar/puppet-concat.git'
  symlinks:
    mcollective: '#{source_dir}'
