---
fixtures:
  repositories:
    inifile: 'git://github.com/cprice-puppet/puppetlabs-inifile.git'
    stdlib: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
    concat: 'git://github.com/ripienaar/puppet-concat.git'
  symlinks:
    mcollective: '#{source_dir}'
