name 'puppetlabs-mcollective'
version '0.0.2'
dependency 'cprice404/inifile'
description 'Module to install and configure mcollective.'
project_page 'https://github.com/puppetlabs/puppetlabs-mcollective'
